/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PaiementConfirmeRouteImport } from './routes/paiement-confirme'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChauffeurRouteImport } from './routes/chauffeur'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuiviTokenRouteImport } from './routes/suivi.$token'
import { Route as AuthenticatedEspaceClientRouteImport } from './routes/_authenticated/espace-client'
import { Route as AuthenticatedEspaceChauffeurRouteImport } from './routes/_authenticated/espace-chauffeur'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFactureIdRouteImport } from './routes/_authenticated/facture.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementConfirmeRoute = PaiementConfirmeRouteImport.update({
  id: '/paiement-confirme',
  path: '/paiement-confirme',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeurRoute = ChauffeurRouteImport.update({
  id: '/chauffeur',
  path: '/chauffeur',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviTokenRoute = SuiviTokenRouteImport.update({
  id: '/suivi/$token',
  path: '/suivi/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceClientRoute =
  AuthenticatedEspaceClientRouteImport.update({
    id: '/espace-client',
    path: '/espace-client',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEspaceChauffeurRoute =
  AuthenticatedEspaceChauffeurRouteImport.update({
    id: '/espace-chauffeur',
    path: '/espace-chauffeur',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFactureIdRoute = AuthenticatedFactureIdRouteImport.update({
  id: '/facture/$id',
  path: '/facture/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chauffeur': typeof ChauffeurRoute
  '/login': typeof LoginRoute
  '/paiement-confirme': typeof PaiementConfirmeRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace-chauffeur': typeof AuthenticatedEspaceChauffeurRoute
  '/espace-client': typeof AuthenticatedEspaceClientRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/facture/$id': typeof AuthenticatedFactureIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chauffeur': typeof ChauffeurRoute
  '/login': typeof LoginRoute
  '/paiement-confirme': typeof PaiementConfirmeRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/espace-chauffeur': typeof AuthenticatedEspaceChauffeurRoute
  '/espace-client': typeof AuthenticatedEspaceClientRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/facture/$id': typeof AuthenticatedFactureIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/chauffeur': typeof ChauffeurRoute
  '/login': typeof LoginRoute
  '/paiement-confirme': typeof PaiementConfirmeRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/espace-chauffeur': typeof AuthenticatedEspaceChauffeurRoute
  '/_authenticated/espace-client': typeof AuthenticatedEspaceClientRoute
  '/suivi/$token': typeof SuiviTokenRoute
  '/_authenticated/facture/$id': typeof AuthenticatedFactureIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chauffeur'
    | '/login'
    | '/paiement-confirme'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/espace-chauffeur'
    | '/espace-client'
    | '/suivi/$token'
    | '/facture/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chauffeur'
    | '/login'
    | '/paiement-confirme'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/espace-chauffeur'
    | '/espace-client'
    | '/suivi/$token'
    | '/facture/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/chauffeur'
    | '/login'
    | '/paiement-confirme'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/espace-chauffeur'
    | '/_authenticated/espace-client'
    | '/suivi/$token'
    | '/_authenticated/facture/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChauffeurRoute: typeof ChauffeurRoute
  LoginRoute: typeof LoginRoute
  PaiementConfirmeRoute: typeof PaiementConfirmeRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuiviTokenRoute: typeof SuiviTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement-confirme': {
      id: '/paiement-confirme'
      path: '/paiement-confirme'
      fullPath: '/paiement-confirme'
      preLoaderRoute: typeof PaiementConfirmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeur': {
      id: '/chauffeur'
      path: '/chauffeur'
      fullPath: '/chauffeur'
      preLoaderRoute: typeof ChauffeurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$token': {
      id: '/suivi/$token'
      path: '/suivi/$token'
      fullPath: '/suivi/$token'
      preLoaderRoute: typeof SuiviTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace-client': {
      id: '/_authenticated/espace-client'
      path: '/espace-client'
      fullPath: '/espace-client'
      preLoaderRoute: typeof AuthenticatedEspaceClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/espace-chauffeur': {
      id: '/_authenticated/espace-chauffeur'
      path: '/espace-chauffeur'
      fullPath: '/espace-chauffeur'
      preLoaderRoute: typeof AuthenticatedEspaceChauffeurRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facture/$id': {
      id: '/_authenticated/facture/$id'
      path: '/facture/$id'
      fullPath: '/facture/$id'
      preLoaderRoute: typeof AuthenticatedFactureIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEspaceChauffeurRoute: typeof AuthenticatedEspaceChauffeurRoute
  AuthenticatedEspaceClientRoute: typeof AuthenticatedEspaceClientRoute
  AuthenticatedFactureIdRoute: typeof AuthenticatedFactureIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEspaceChauffeurRoute: AuthenticatedEspaceChauffeurRoute,
  AuthenticatedEspaceClientRoute: AuthenticatedEspaceClientRoute,
  AuthenticatedFactureIdRoute: AuthenticatedFactureIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChauffeurRoute: ChauffeurRoute,
  LoginRoute: LoginRoute,
  PaiementConfirmeRoute: PaiementConfirmeRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuiviTokenRoute: SuiviTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
